#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="$HOME/.config/network-storage"
CONFIG_FILE="$CONFIG_DIR/config.env"
CRED_FILE="$CONFIG_DIR/.smbcredentials"

# ── Load config ───────────────────────────────────────────────────
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: Config file not found at $CONFIG_FILE"
  exit 1
fi
source "$CONFIG_FILE"

echo ""
echo "━━━ Network Storage Setup ━━━"
echo "Server: $SMB_SERVER"

# ── Credentials ───────────────────────────────────────────────────
if [[ -f "$CRED_FILE" ]] && grep -q "^username=" "$CRED_FILE"; then
  SMB_USER=$(grep "^username=" "$CRED_FILE" | cut -d= -f2)
  echo "Using credentials at $CRED_FILE (user: $SMB_USER)"
else
  # Default to guest access — the TUI installer prompts for credentials,
  # or edit ~/.config/network-storage/.smbcredentials manually
  cat > "$CRED_FILE" <<EOF
username=guest
password=
EOF
  chmod 600 "$CRED_FILE"
  echo "Configured guest access (edit $CRED_FILE for authenticated access)"
fi
chmod 600 "$CRED_FILE"

# ── Create mount directories ─────────────────────────────────────
echo ""
echo "Creating mount points..."
sudo mkdir -p "${MOUNT_BASE}/${SMB_SHARE_DOCS}"
sudo mkdir -p "${MOUNT_BASE}/${SMB_SHARE_MEDIA}"

# ── Create systemd mount units ───────────────────────────────────
DOCS_UNIT=$(systemd-escape --path "${MOUNT_BASE}/${SMB_SHARE_DOCS}")
MEDIA_UNIT=$(systemd-escape --path "${MOUNT_BASE}/${SMB_SHARE_MEDIA}")

echo "Creating systemd mount units..."

# Documents mount
sudo tee "/etc/systemd/system/${DOCS_UNIT}.mount" > /dev/null <<EOF
[Unit]
Description=SMB mount for documents (${SMB_SERVER})
After=network-online.target tailscaled.service
Wants=network-online.target

[Mount]
What=//${SMB_SERVER}/${SMB_SHARE_DOCS}
Where=${MOUNT_BASE}/${SMB_SHARE_DOCS}
Type=cifs
Options=credentials=${CRED_FILE},uid=$(id -u),gid=$(id -g),file_mode=0664,dir_mode=0775,nofail,_netdev,x-systemd.automount,x-systemd.idle-timeout=300
TimeoutSec=30

[Install]
WantedBy=multi-user.target
EOF

# Documents automount
sudo tee "/etc/systemd/system/${DOCS_UNIT}.automount" > /dev/null <<EOF
[Unit]
Description=Automount SMB documents (${SMB_SERVER})
After=network-online.target tailscaled.service
Wants=network-online.target

[Automount]
Where=${MOUNT_BASE}/${SMB_SHARE_DOCS}
TimeoutIdleSec=300

[Install]
WantedBy=multi-user.target
EOF

# Media mount
sudo tee "/etc/systemd/system/${MEDIA_UNIT}.mount" > /dev/null <<EOF
[Unit]
Description=SMB mount for media (${SMB_SERVER})
After=network-online.target tailscaled.service
Wants=network-online.target

[Mount]
What=//${SMB_SERVER}/${SMB_SHARE_MEDIA}
Where=${MOUNT_BASE}/${SMB_SHARE_MEDIA}
Type=cifs
Options=credentials=${CRED_FILE},uid=$(id -u),gid=$(id -g),file_mode=0664,dir_mode=0775,nofail,_netdev,x-systemd.automount,x-systemd.idle-timeout=300
TimeoutSec=30

[Install]
WantedBy=multi-user.target
EOF

# Media automount
sudo tee "/etc/systemd/system/${MEDIA_UNIT}.automount" > /dev/null <<EOF
[Unit]
Description=Automount SMB media (${SMB_SERVER})
After=network-online.target tailscaled.service
Wants=network-online.target

[Automount]
Where=${MOUNT_BASE}/${SMB_SHARE_MEDIA}
TimeoutIdleSec=0

[Install]
WantedBy=multi-user.target
EOF

# Reload and enable
sudo systemctl daemon-reload
sudo systemctl enable --now "${DOCS_UNIT}.automount"
sudo systemctl enable --now "${MEDIA_UNIT}.automount"

echo "Mounts configured and enabled"

# ── Mount shares now ──────────────────────────────────────────────
echo ""
echo "Mounting shares..."
sudo systemctl start "${DOCS_UNIT}.mount" || echo "WARN: Could not mount documents (server may be offline)"
sudo systemctl start "${MEDIA_UNIT}.mount" || echo "WARN: Could not mount media (server may be offline)"

# ── Create local directories & initial sync ───────────────────────
echo ""
echo "Setting up document sync..."
for folder in $SYNC_FOLDERS; do
  mkdir -p "$HOME/$folder"
done

# Create unison profiles directory
mkdir -p "$HOME/.unison"

# Generate unison profile for document sync
cat > "$HOME/.unison/network-storage.prf" <<EOF
# Network Storage sync profile
# Auto-generated by network-storage setup

# Roots
root = ${MOUNT_BASE}/${SMB_SHARE_DOCS}
root = ${HOME}

# Folders to sync
$(for folder in $SYNC_FOLDERS; do echo "path = ${folder}"; done)

# Sync options
auto = true
batch = true
confirmbigdeletes = false
prefer = newer
times = true
perms = 0
dontchmod = true

# Ignore patterns
ignore = Name {.DS_Store}
ignore = Name {Thumbs.db}
ignore = Name {*.tmp}
ignore = Name {.Trash-*}
ignore = Name {.unison*}
EOF

echo "Unison profile created at ~/.unison/network-storage.prf"

# Run initial sync if mount is available
if mountpoint -q "${MOUNT_BASE}/${SMB_SHARE_DOCS}" 2>/dev/null; then
  echo "Running initial sync (this may take a while)..."
  unison network-storage || echo "WARN: Initial sync had issues — run 'unison network-storage' manually to resolve"
else
  echo "Documents share not mounted — skipping initial sync"
  echo "Run 'unison network-storage' once the server is available"
fi

# ── Media symlink ─────────────────────────────────────────────────
echo ""
echo "Setting up media symlink..."
if [[ -L "$HOME/Media" ]]; then
  echo "~/Media symlink already exists"
elif [[ -d "$HOME/Media" ]]; then
  echo "WARN: ~/Media is a regular directory — not replacing"
  echo "  Remove it manually and re-run setup to create the symlink"
else
  ln -s "${MOUNT_BASE}/${SMB_SHARE_MEDIA}" "$HOME/Media"
  echo "Created ~/Media -> ${MOUNT_BASE}/${SMB_SHARE_MEDIA}"
fi

# ── Sync timer ────────────────────────────────────────────────────
echo ""
echo "Setting up periodic sync timer..."

mkdir -p "$HOME/.config/systemd/user"

cat > "$HOME/.config/systemd/user/network-storage-sync.service" <<EOF
[Unit]
Description=Sync documents with network storage
After=network-online.target

[Service]
Type=oneshot
ExecStart=${CONFIG_DIR}/sync.sh
Environment=HOME=${HOME}
EOF

cat > "$HOME/.config/systemd/user/network-storage-sync.timer" <<EOF
[Unit]
Description=Periodic document sync with network storage

[Timer]
OnBootSec=2min
OnUnitActiveSec=${SYNC_INTERVAL}min
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now network-storage-sync.timer

echo ""
echo "━━━ Setup complete ━━━"
echo ""
echo "  Documents sync: ~/Documents, ~/Music, ~/Pictures, ~/Videos"
echo "  Sync interval:  every ${SYNC_INTERVAL} minutes"
echo "  Media access:   ~/Media (network mount, no local copy)"
echo "  Server:         ${SMB_SERVER}"
echo ""
echo "  Manual sync:    unison network-storage"
echo "  Check status:   systemctl --user status network-storage-sync.timer"
echo "  Edit config:    $CONFIG_FILE"
