pragma Singleton
import QtQuick

QtObject {
    // Material You palette — generated by matugen
<* for name, value in colors *>
    readonly property color {{name}}: "{{value.default.hex}}"
<* endfor *>

    // Glass effect helpers
    readonly property color glass: Qt.rgba(background.r, background.g, background.b, 0.75)
    readonly property color glassBorder: Qt.rgba(outline_variant.r, outline_variant.g, outline_variant.b, 0.5)

    // Semantic aliases for backward compatibility with QML modules
    readonly property color text: on_surface
    readonly property color subtext0: on_surface_variant
    readonly property color subtext1: on_surface_variant
    readonly property color accent: primary
    readonly property color surface0: surface_container
    readonly property color surface1: surface_container_high
    readonly property color surface2: surface_container_highest
    readonly property color overlay0: outline_variant
    readonly property color overlay1: outline
    readonly property color mantle: surface_container_lowest
    readonly property color crust: surface_dim
    readonly property color red: error
    readonly property color green: tertiary
    readonly property color blue: secondary
    readonly property color yellow: tertiary_container
    readonly property color peach: tertiary
    readonly property color teal: secondary_container
    readonly property color sky: secondary
    readonly property color sapphire: secondary
    readonly property color rosewater: tertiary_fixed_dim
    readonly property color lavender: secondary_fixed
    readonly property color flamingo: tertiary_fixed
    readonly property color maroon: error_container
    readonly property color mauve: primary
}
