pragma Singleton
import QtQuick

QtObject {
    // Material You palette — generated by matugen

    readonly property color background: "#1a1110"

    readonly property color error: "#ffb4ab"

    readonly property color error_container: "#93000a"

    readonly property color inverse_on_surface: "#392e2c"

    readonly property color inverse_primary: "#904b3e"

    readonly property color inverse_surface: "#f1dfdb"

    readonly property color on_background: "#f1dfdb"

    readonly property color on_error: "#690005"

    readonly property color on_error_container: "#ffdad6"

    readonly property color on_primary: "#561e15"

    readonly property color on_primary_container: "#ffdad4"

    readonly property color on_primary_fixed: "#3a0a04"

    readonly property color on_primary_fixed_variant: "#733429"

    readonly property color on_secondary: "#442a25"

    readonly property color on_secondary_container: "#ffdad4"

    readonly property color on_secondary_fixed: "#2c1511"

    readonly property color on_secondary_fixed_variant: "#5d3f3a"

    readonly property color on_surface: "#f1dfdb"

    readonly property color on_surface_variant: "#d8c2be"

    readonly property color on_tertiary: "#3d2e04"

    readonly property color on_tertiary_container: "#fae0a6"

    readonly property color on_tertiary_fixed: "#251a00"

    readonly property color on_tertiary_fixed_variant: "#564519"

    readonly property color outline: "#a08c89"

    readonly property color outline_variant: "#534340"

    readonly property color primary: "#ffb4a6"

    readonly property color primary_container: "#733429"

    readonly property color primary_fixed: "#ffdad4"

    readonly property color primary_fixed_dim: "#ffb4a6"

    readonly property color scrim: "#000000"

    readonly property color secondary: "#e7bdb5"

    readonly property color secondary_container: "#5d3f3a"

    readonly property color secondary_fixed: "#ffdad4"

    readonly property color secondary_fixed_dim: "#e7bdb5"

    readonly property color shadow: "#000000"

    readonly property color source_color: "#ba2a16"

    readonly property color surface: "#1a1110"

    readonly property color surface_bright: "#423735"

    readonly property color surface_container: "#271d1c"

    readonly property color surface_container_high: "#322826"

    readonly property color surface_container_highest: "#3d3230"

    readonly property color surface_container_low: "#231918"

    readonly property color surface_container_lowest: "#140c0b"

    readonly property color surface_dim: "#1a1110"

    readonly property color surface_tint: "#ffb4a6"

    readonly property color surface_variant: "#534340"

    readonly property color tertiary: "#ddc48c"

    readonly property color tertiary_container: "#564519"

    readonly property color tertiary_fixed: "#fae0a6"

    readonly property color tertiary_fixed_dim: "#ddc48c"


    // Glass effect helpers
    readonly property color glass: Qt.rgba(background.r, background.g, background.b, 0.75)
    readonly property color glassBorder: Qt.rgba(outline_variant.r, outline_variant.g, outline_variant.b, 0.5)

    // Semantic aliases for backward compatibility with QML modules
    readonly property color text: on_surface
    readonly property color subtext0: on_surface_variant
    readonly property color subtext1: on_surface_variant
    readonly property color accent: primary
    readonly property color surface0: surface_container
    readonly property color surface1: surface_container_high
    readonly property color surface2: surface_container_highest
    readonly property color overlay0: outline_variant
    readonly property color overlay1: outline
    readonly property color mantle: surface_container_lowest
    readonly property color crust: surface_dim
    readonly property color red: error
    readonly property color green: tertiary
    readonly property color blue: secondary
    readonly property color yellow: tertiary_container
    readonly property color peach: tertiary
    readonly property color teal: secondary_container
    readonly property color sky: secondary
    readonly property color sapphire: secondary
    readonly property color rosewater: tertiary_fixed_dim
    readonly property color lavender: secondary_fixed
    readonly property color flamingo: tertiary_fixed
    readonly property color maroon: error_container
    readonly property color mauve: primary
}
